export const HTTP_STATUS_CODE = {
	SUCCESS: 200,
	CREATED: 201,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	VALIDATION_ERROR: 422,
	NOT_FOUND: 404,
	INTERNAL_SERVER_ERROR: 500,
	FORBIDDEN: 403,
	CONFLICT: 409,
} as const;

export const ERROR_CODE = {
	VALIDATION_ERROR: "VALIDATION_ERROR",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	NOT_FOUND: "NOT_FOUND",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	BAD_REQUEST: "BAD_REQUEST",
} as const;
